spring:
  application:
    name: "user-center"
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: "jdbc:mysql://localhost:3306/cxy?useUnicode=true&characterEncoding=utf8"
    username: "root"
    password: "187900cw"
  session:
    timeout: 86400
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false